### PR TITLE
Update to latest Boot and sassc

### PR DESCRIPTION
**Pull request by bobby**
This addresses mathias/boot-sassc#1, and brings the usage of both the Boot and sassc APIs up to latest.

@mathias could you cut a release and push this to Clojars as mathias/boot-sassc?  That would allow me to stop relying on local build/install.

### CODE REVIEW

**Comment by bobby** [comment]
@mathias I know you have been traveling, so no rush, but have you considered this pull request?  I've been using my fork for my builds for about a week with good success.

**Comment by mathias** [comment]
I haven't had a chance to look, but I'm pulling it down now to this work laptop. What's the reason for putting this under the `mathias` namespace?

**Comment by bobby** [comment]
Naming as per guidance in https://github.com/boot-clj/boot/wiki/Task-Writer%27s-Guide.

**Comment by mathias** [comment]
LGTM. Thank you!

**Comment by mathias** [comment]
@bobby 0.1.1 has been pushed to Clojars. Thanks for this!

**Pull request merged**
